-   id: ruff
    name: ruff
    description: ''
    entry: ruff
    language: python
    'types': [python]
    args: ["--fix"]
    require_serial: false
    additional_dependencies: []
    minimum_pre_commit_version: '0'
